### ISSUE TITLE
error: redeclared as different kind of symbol

### ISSUE THREAD

**Issue by cankav** [lamerman/cpp-lru-cache#13]
The example contains the following definition:

`cache::lru_cache<std::string, std::string> cache(3);`

This conflicts with the namespace definition in lrucache.hpp

`namespace cache {`

and produces 'redeclared as different kind of symbol' error on g++ (Debian 4.7.2-5) 4.7.2. The comment at the bottom of the lrucache.hpp suggest namespace was named 'lru' at some point, which works fine. I suggest changing the namespace definition back to lru.

**Comment by lamerman** [comment]
@cankav I'll have a look soon

**Comment by lamerman** [comment]
Fixed in #15
