### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by vicentebolea** [lamerman/cpp-lru-cache#16]
Have you thought about naming this library, I believe (I could not find it) there is not library which uses a map and linked list for a lru cache in c++. This library is quite useful and it would be great to have it in the linux packages repositories.

I can help you out making the rpm packages afterwards :+1:

**Comment by lamerman** [comment]
Hi, Vicente.

I'm not very familiar with the procedure of publishing packages to linux distributions. Is there some review process for packages?

**Comment by vicentebolea** [comment]
Hi, first step is to create the RPM or DEB package. Once we have it, we can upload it to launchpad or opensuse software (The ones I know). 
AFAIK, we can run our own repo (like a github) and then later we can propose it for the Linux distributions.

**Comment by lamerman** [comment]
@vicentebolea I think it's in general ok to publish it to launchpad or similar repositories but I would prefer to leave current build systems like cmake. As I understand it does not bother in any way to create packages.
