### ISSUE TITLE
The incoming parameter 'value' is  smart pointer 'std::shared_ptr'

### ISSUE THREAD

**Issue by youzp** [lamerman/cpp-lru-cache#21]
If the incoming parameter 'value' is smart pointer 'std::shared_ptr', the smart pointer will be released two times in function put().
`_cache_items_map.erase(last->first);
_cache_items_list.pop_back();`

**Comment by youzp** [comment]
sorry,my bad, just ignore this.

**Comment by lamerman** [comment]
@youzp I looked at the issue but did not notice the problem.
